# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  :app_id: 467638323400644
  :app_secret: 8046daee11aa5e370c1239a922e0f18e

  secret_key_base: 8d7d80857b7d8ec9b1ec26e1195379c944a8d0487c9e5b027c6e8ed81dbd74f91aa65b6d725de88e914cf73b780c64ad3ea5c97ac8c6f84fdea35b6e3fa91199

test:
  secret_key_base: 1f8dfbf0fe10d83e56abe9ef7e2eda359788a96ea4d324280b666264b756f8209aae95d40cc45d715d47fc7f07f8bc686d1ce2649e4d274bd7bf85e91a73ef81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  :app_id: 467638323400644
  :app_secret: 8046daee11aa5e370c1239a922e0f18e
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
